"""
model_utils.py
Preprocessing utilities that mirror question1.ipynb for single-row predictions.
Loaded once at app startup and used by every prediction request.
"""

import json
import os
import numpy as np
import pandas as pd
import tensorflow as tf

# ── School lookup table ────────────────────────────────────────────────────────
# Populated from model/colegios.json (generated by build_colegios.py).
# Key: str(DANE code), Value: {nombre, municipio, area_urbano, bilingue, ...}

def _load_colegios() -> dict:
    path = os.path.join(os.path.dirname(__file__), "model", "colegios.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)

COLEGIOS: dict = _load_colegios()

# Grouped by municipio for fast dropdown filtering
COLEGIOS_BY_MCPIO: dict[int, list[dict]] = {}
for _code, _info in COLEGIOS.items():
    _m = _info["municipio"]
    COLEGIOS_BY_MCPIO.setdefault(_m, []).append({"code": _code, **_info})

# ── Categorical lookup tables ──────────────────────────────────────────────────

MUNICIPIOS_CESAR = {
    20001: "Valledupar",
    20011: "Aguachica",
    20013: "Agustín Codazzi",
    20032: "Astrea",
    20045: "Becerril",
    20060: "Bosconia",
    20175: "Chimichagua",
    20178: "Chiriguaná",
    20228: "Curumaní",
    20238: "El Copey",
    20250: "El Paso",
    20295: "Gamarra",
    20310: "González",
    20383: "La Gloria",
    20400: "La Jagua de Ibirico",
    20443: "Manaure",
    20517: "Pailitas",
    20550: "Pelaya",
    20570: "Pueblo Bello",
    20614: "Río de Oro",
    20621: "La Paz",
    20710: "San Alberto",
    20750: "San Diego",
    20770: "San Martín",
    20787: "Tamalameque",
}

# Human-readable labels for education levels (key = raw CSV value with cp1252 chars)
EDUCATION_LABELS = {
    "Ninguno":                                  "Ninguno",
    "No Aplica":                                "No aplica",
    "No sabe":                                  "No sabe",
    "Primaria incompleta":                      "Primaria incompleta",
    "Primaria completa":                        "Primaria completa",
    "Secundaria (Bachillerato) incompleta":     "Bachillerato incompleto",
    "Secundaria (Bachillerato) completa":       "Bachillerato completo",
    "Técnica o tecnológica incompleta":         "Técnica/Tecnológica incompleta",
    "Técnica o tecnológica completa":           "Técnica/Tecnológica completa",
    "Educación profesional incompleta":         "Profesional incompleto",
    "Educación profesional completa":           "Profesional completo",
    "Postgrado":                                "Postgrado",
}

PERIODOS_LABELS = {
    20142: "2014-2",
    20151: "2015-1",
    20152: "2015-2",
    20161: "2016-1",
    20162: "2016-2",
    20171: "2017-1",
    20172: "2017-2",
    20181: "2018-1",
    20191: "2019-1",
    20194: "2019-4",
    20201: "2020-1",
    20211: "2021-1",
    20221: "2022-1",
    20224: "2022-4",
}

# Cuartos mapping (raw value → model category)
CUARTOS_MAP = {
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6+": "6+",
}

# Personas mapping (raw value → model category)
PERSONAS_MAP = {
    "1 a 2": "1 a 2",
    "3 a 4": "3 a 4",
    "5 a 6": "5 a 6",
    "7 a 8": "7 a 8",
    "9 o más": "9 o más",
    "12 o más": "12 o más",
}


class ModelLoader:
    """Loads and caches model + artifacts at startup."""

    def __init__(self, model_dir: str):
        self.model_dir = model_dir
        self.model = None
        self.feature_columns: list[str] = []
        self.model_info: dict = {}
        self._load()

    def _load(self):
        model_path = os.path.join(self.model_dir, "model.keras")
        feat_path  = os.path.join(self.model_dir, "feature_columns.json")
        info_path  = os.path.join(self.model_dir, "model_info.json")

        if not os.path.exists(model_path):
            raise FileNotFoundError(
                f"Model not found at {model_path}.\n"
                "Run  python export_model.py  first to train and save the model."
            )

        self.model = tf.keras.models.load_model(model_path)
        with open(feat_path) as f:
            self.feature_columns = json.load(f)
        with open(info_path) as f:
            self.model_info = json.load(f)

    def predict(self, user_inputs: dict) -> float:
        """
        Build a preprocessed feature row from user_inputs dict and return prediction.

        user_inputs keys (all required):
            periodo              int   e.g. 20221
            cole_area_urbano     bool  True=Urbano, False=Rural
            cole_bilingue        bool
            cole_calendario_a    bool  True=A, False=B
            cole_oficial         bool  True=Oficial, False=No oficial
            estu_masculino       bool  True=Masculino, False=Femenino
            fami_tieneautomovil  bool
            fami_tienecomputador bool
            fami_tieneinternet   bool
            fami_tienelavadora   bool
            cole_caracter        str   e.g. "ACADÉMICO"
            cole_jornada         str   e.g. "MAÑANA"
            estu_nacionalidad    str   e.g. "COLOMBIA"
            fami_cuartoshogar    str   e.g. "3"  (after mapping)
            fami_educacionmadre  str   raw education label
            fami_educacionpadre  str   raw education label
            fami_estratovivienda str   e.g. "Estrato 2"
            fami_personashogar   str   e.g. "3 a 4"
            cole_cod_mcpio_ubicacion  int   DANE municipality code
            estu_cod_reside_mcpio     int   DANE municipality code
            cole_cod_dane_establecimiento  int  (optional, 0 if unknown)
            cole_cod_dane_sede            int  (optional, 0 if unknown)
        """
        row = self._build_feature_row(user_inputs)
        x = row.to_numpy(dtype=np.float32).reshape(1, -1)
        pred = self.model.predict(x, verbose=0)[0][0]
        return float(pred)

    def _build_feature_row(self, ui: dict) -> pd.Series:
        """Reconstruct a single preprocessed row aligned to feature_columns."""

        # Start with a dict of all-zero values
        raw: dict = {}

        # ── Numeric ──
        raw["periodo"] = float(ui["periodo"])

        # ── Binary booleans ──
        raw["cole_area_urbano"]     = bool(ui["cole_area_urbano"])
        raw["cole_bilingue"]        = bool(ui["cole_bilingue"])
        raw["cole_calendario_a"]    = bool(ui["cole_calendario_a"])
        raw["cole_oficial"]         = bool(ui["cole_oficial"])
        raw["estu_masculino"]       = bool(ui["estu_masculino"])
        raw["fami_tieneautomovil"]  = bool(ui["fami_tieneautomovil"])
        raw["fami_tienecomputador"] = bool(ui["fami_tienecomputador"])
        raw["fami_tieneinternet"]   = bool(ui["fami_tieneinternet"])
        raw["fami_tienelavadora"]   = bool(ui["fami_tienelavadora"])

        # ── Categorical OHE columns: set the right one to 1 ──
        # For each OHE'd column like "cole_caracter_TÉCNICO", we set it to 1
        # if it matches the user's selection. All others stay 0.

        def _set_ohe(prefix: str, value: str):
            col = f"{prefix}_{value}"
            if col in raw:
                raw[col] = 1
            else:
                raw[col] = 1  # will be dropped if not in feature_columns at reindex

        _set_ohe("cole_caracter",               str(ui["cole_caracter"]))
        _set_ohe("cole_cod_mcpio_ubicacion",     str(int(ui["cole_cod_mcpio_ubicacion"])))
        _set_ohe("estu_cod_reside_mcpio",        str(int(ui["estu_cod_reside_mcpio"])))
        _set_ohe("cole_jornada",                 str(ui["cole_jornada"]))
        _set_ohe("estu_nacionalidad",            str(ui["estu_nacionalidad"]))
        _set_ohe("fami_cuartoshogar",            str(ui["fami_cuartoshogar"]))
        _set_ohe("fami_educacionmadre",          str(ui["fami_educacionmadre"]))
        _set_ohe("fami_educacionpadre",          str(ui["fami_educacionpadre"]))
        _set_ohe("fami_estratovivienda",         str(ui["fami_estratovivienda"]))
        _set_ohe("fami_personashogar",           str(ui["fami_personashogar"]))

        estab = ui.get("cole_cod_dane_establecimiento")
        if estab:
            _set_ohe("cole_cod_dane_establecimiento", str(int(estab)))

        sede = ui.get("cole_cod_dane_sede")
        if sede:
            _set_ohe("cole_cod_dane_sede", str(int(sede)))

        # Build a Series aligned to the model's feature_columns
        series = pd.Series(raw)
        series = series.reindex(self.feature_columns, fill_value=0)
        return series
